
namespace: default
nameOverride: microservicio
deploymentName: microservicioEmail-deployment

replicaCount: 1
image:
  repository: juancamco/microservicio
  tag: "v1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"
serviceAccount:
  create: false
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  CPUUtilizationPercentage: 70

ingress:
  enabled: false
